In [29]:
# pandas.DataFrame.T

# Transpose index and columns.
# Reflect the DataFrame over its main diagonal by writing rows as columns and vice-versa.
# The property T is an accessor to the method transpose().

In [30]:
import pandas as pd
df = {'col1': [22, 4], 'col2:': [33, 2]}
df1 = pd.DataFrame(data=df)
df1

col1  col2:
0    22     33
1     4      2

In [31]:
df1_transposed = df1.T
df1_transposed


0  1
col1   22  4
col2:  33  2

In [32]:
df = {'name':['Alexei', 'Sam', 'Marion'], 'address': ['2007 Cambridge', '1428 Mission', '2056 Rodesian']}
df2 = pd.DataFrame(data=df)
df2

name         address
0  Alexei  2007 Cambridge
1     Sam    1428 Mission
2  Marion   2056 Rodesian

In [33]:
df2_transposed = df2.T
df2_transposed

0             1              2
name             Alexei           Sam         Marion
address  2007 Cambridge  1428 Mission  2056 Rodesian

In [34]:
df2.dtypes

name       object
address    object
dtype: object

In [35]:
# numpy.ravel - return a contiguous flattened array
import numpy as np

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.ravel(x))

[1 2 3 4 5 6 7 8]


In [36]:
x = np.array([[2, 5, 3], [1, 4, 8]])
print(np.ravel(x))

[2 5 3 1 4 8]


In [37]:
# Ravel and transpose

print(np.ravel(x.T))

[2 1 5 4 3 8]


In [38]:
# Note this doesn't work for non homogenous dimension arrays
# e.g: 

x = np.array([[2, 3, 5], [4, 5, 6, 7]])
print(np.ravel(x))

[list([2, 3, 5]) list([4, 5, 6, 7])]
